spring:
  datasource:
    url: jdbc:h2:mem:users_db;DB_CLOSE_DELAY=-1;
    username: user_admin
    password: test
    driver-class-name: org.h2.Driver
    datasource:
      hikari:
        enabled: false
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
        defer-datasource-initialization: true
        ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  properties:
    hibernate:
      temp:
        use_jdbc_metadata_defaults: false
    jdbc:
      time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: "/user-service"

security:
  encryption:
    key: "ecf0cfb1-22d0-421e-9761-f8c6a67d492a"
  jwt:
    secret-key: "a464424b-4d34-4d81-8fda-9cf61cd2ec99"
