spring:
  datasource:
    url: jdbc:h2:mem:users_db
    username: admin
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  properties:
    hibernate:
      temp:
        use_jdbc_metadata_defaults: false
    jdbc:
      time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: "/user-service"